defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

max_steps: 100
num_episodes: 10
seed: 0
gamma: 0.98
save_log: false
replay_path: None
env_name: &env_name "MyMiniGrid-FourRooms-v0"
env:
  _target_: uncertain_worms.environments.minigrid.minigrid_env.MinigridEnvironment
  fully_obs: false
  env_name: ${env_name}
agent:
  _target_: uncertain_worms.policies.random_policy.RandomPolicy
  fully_obs: false
  actions: [0, 1, 2]